# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sandraschool
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam: 
    role: arn:aws:iam::651706766552:role/FullAccessLambdaDynamodb
  httpApi:
    cors: true

functions:

    GetMessages:
        handler: functions/GetMessages/index.handler
        events:
            - httpApi:
                  path: /messages
                  method: get
    GetMessage:
        handler: functions/GetMessage/index.handler
        events:
            - httpApi:
                  path: /messages/{id}
                  method: get

    PostMessage:
        handler: functions/PostMessage/index.handler
        events:
            - httpApi:
                  path: /messages
                  method: post
    UpdateMessage:
        handler: functions/UpdateMessage/index.handler
        events:
            - httpApi:
                  path: /messages/{id}
                  method: put
    DeleteMessage:
        handler: functions/DeleteMessage/index.handler
        events:
            - httpApi:
                  path: /messages/{id}
                  method: delete
resources:
    Resources:
        shuiMessages:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: shuiMessages
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST